### ISSUE TITLE
Add repository info data to jscpd-report.json

### ISSUE THREAD

**Issue by hata6502** [hata6502/jscpd-service#10]
## Motivation

By adding the repository `revision` info data to `jscpd-report.json`, it makes `viewer` package can show repository info. 

![Screenshot from 2021-03-25 10-51-49](https://user-images.githubusercontent.com/7702653/112406798-302fa780-8d58-11eb-908d-2be21d6bad55.png)

## How to

Current `jscpd-report.json`
```jsonc
{
  "statistics": {
    "detectionDate": "2021-03-20T12:51:04.633Z",
    "formats": {
      // ...
    },
    "total": {
      // ...
    }
  },
  // ...
}
```

Need to
```jsonc
{
  "statistics": {
    "detectionDate": "2021-03-20T12:51:04.633Z",
    "revision": "47a5f315317296ca64d94a99361afdfb8a3da15c",  // Add revision info
    "formats": {
      // ...
    },
    "total": {
      // ...
    }
  },
  // ...
}
```

Will implement to
- `packages/crawler/src/report.ts`

**Comment by hata6502** [comment]
@kuromike0629

**Comment by kuromike0629** [comment]
Oops...Sorry, I didn't recoginize directory path was changed.
I will fix and send pull request again.

**Comment by kuromike0629** [comment]
fix and sent PR.
