### ISSUE TITLE
Missing package-lock.json for crawler package

### ISSUE THREAD

**Issue by kuromike0629** [hata6502/jscpd-service#14]
When run "$act -j deploy" faild to build Dockerfile because of missing package-lock.json.

**Comment by hata6502** [comment]
Sorry!
`package-lock.json` is not existed because of npm v7 monorepo. 
https://docs.npmjs.com/cli/v7/using-npm/workspaces

To fix it, I propose to use Webpack.
Please see:https://github.com/hata6502/jscpd-service/issues/8
